# Generated by Django 5.0.6 on 2024-05-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_report_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='title',
            field=models.CharField(default='teste', max_length=50),
        ),
    ]
