# Generated by Django 5.0.6 on 2024-05-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_report_api', '0002_maintenancereport_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='shift',
            field=models.CharField(choices=[('M', 'Morning Shift'), ('A', 'Afternoon Shift'), ('N', 'Night Shift')], default='M', max_length=1),
        ),
    ]
