# Generated by Django 5.0.6 on 2024-05-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_report_api', '0003_maintenancereport_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancereport',
            name='sift',
        ),
    ]
