# Generated by Django 5.0.6 on 2024-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_report_api', '0007_executor_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancereport',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'Check'), ('3', 'Closed')], default='1', max_length=1),
        ),
    ]
