# Generated by Django 5.0.6 on 2024-05-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_report_api', '0009_remove_maintenancereport_number_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='executors',
            field=models.ManyToManyField(through='maintenance_report_api.ExecutorReport', to='maintenance_report_api.executor'),
        ),
    ]
