# Generated by Django 5.0.6 on 2024-05-29 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_report_api', '0010_maintenancereport_executors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('activate', models.CharField(choices=[('1', 'activate'), ('2', 'inactive')], default='1', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='executor',
            name='ativo',
        ),
        migrations.AddField(
            model_name='executor',
            name='activated',
            field=models.CharField(choices=[('1', 'activate'), ('2', 'inactive')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('activate', models.CharField(choices=[('1', 'activate'), ('2', 'inactive')], default='1', max_length=1)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance_report_api.line')),
            ],
        ),
    ]
