# Generated by Django 5.0.6 on 2024-05-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_report_api', '0011_line_remove_executor_ativo_executor_activated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancereport',
            name='line_machine',
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='line',
            field=models.CharField(default='auto_complete', max_length=100),
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='machine',
            field=models.CharField(default='auto_complete', max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
