# Generated by Django 5.0.6 on 2024-06-03 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_report_api', '0012_remove_maintenancereport_line_machine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancereport',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance_report_api.line'),
        ),
        migrations.AlterField(
            model_name='maintenancereport',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance_report_api.machine'),
        ),
    ]
